fetchmail:
  cron: "*/12 * * * *"
  class: FetchMailWorker
  description: Fetch Mail
  queue: fetch_queue
queuemail:
  cron: "*/12 * * * *"
  class: QueueMailWorker
  description: Queue Mail for Sending
  queue: queue_queue
