fetchmail:
  cron: "* * * * *"
  class: FetchMailJob
  description: Fetch Mail
  queue: fetch_queue
queuemail:
  cron: "* * * * *"
  class: QueueMailJob
  description: Queue Mail for Sending
  queue: process_queue
